### ISSUE TITLE
Android build failing on Hypertrack package

### ISSUE THREAD

**Issue by maslowproject** [hypertrack/react-native-hypertrack#21]
I am trying to create an Android build for a React Native application. In the /android directory of my project I run the command `fastlane alpha` and this is the error I end with:

> :react-native-hypertrack:processReleaseResources
> :app:processReleaseResources
> :app:generateReleaseSources
> :react-native-hypertrack:generateReleaseSources
> :react-native-hypertrack:compileReleaseJavaWithJavac/Users/josh/Documents/WorkProjects/Trucke/frontend_native/truckepal/node_modules/react-native-hypertrack/android/src/main/java/io/hypertrack/RNHyperTrackPackage.java:19: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> Note: /Users/josh/Documents/WorkProjects/Trucke/frontend_native/truckepal/node_modules/react-native-hypertrack/android/src/main/java/io/hypertrack/RNHyperTrackModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-hypertrack:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 38s
> 95 actionable tasks: 73 executed, 22 up-to-date
> 
>         from /Users/josh/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/gradle.rb:50:in `run'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
>         from Fastfile:44:in `block (2 levels) in parsing_binding'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
>         from /Users/josh/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
>         from /Users/josh/.rvm/rubies/ruby-2.4.1/bin/fastlane:22:in `load'
>         from /Users/josh/.rvm/rubies/ruby-2.4.1/bin/fastlane:22:in `<main>'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `eval'
>         from /Users/josh/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `<main>

I'm not sure if don't have the correct java files or not. I've upgraded to the most recent version of this package.

Versions:
react-native: 0.55.4
react-native-hypertrack: ^3.1.6

This is what my android/build.gradle file looks like:

> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     repositories {
>         jcenter()
>         maven {
>             url 'https://maven.google.com/'
>             name 'Google'
>         }
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.0.1'
>         // Detox
>         // classpath 'com.palantir:jacoco-coverage:0.4.0'
>         // react-native-firebase
>         classpath 'com.google.gms:google-services:3.1.0'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // Detox
>             // react-native-firebase
>             url "https://maven.google.com"
>         }
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/node_modules/react-native/android"
>         }
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
> 
>         maven { url 'http://hypertrack-android-sdk.s3-website-us-west-2.amazonaws.com/' }
>     }
> }
> 

And my android/app/build.gradle file:

> apply plugin: "com.android.application"
> 
> import com.android.build.OutputFile
> 
> /**
>  * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
>  * and bundleReleaseJsAndAssets).
>  * These basically call `react-native bundle` with the correct arguments during the Android build
>  * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
>  * bundle directly from the development server. Below you can see all the possible configurations
>  * and their defaults. If you decide to add a configuration block, make sure to add it before the
>  * `apply from: "../../node_modules/react-native/react.gradle"` line.
>  *
>  * project.ext.react = [
>  *   // the name of the generated asset file containing your JS bundle
>  *   bundleAssetName: "index.android.bundle",
>  *
>  *   // the entry file for bundle generation
>  *   entryFile: "index.android.js",
>  *
>  *   // whether to bundle JS and assets in debug mode
>  *   bundleInDebug: false,
>  *
>  *   // whether to bundle JS and assets in release mode
>  *   bundleInRelease: true,
>  *
>  *   // whether to bundle JS and assets in another build variant (if configured).
>  *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
>  *   // The configuration property can be in the following formats
>  *   //         'bundleIn${productFlavor}${buildType}'
>  *   //         'bundleIn${buildType}'
>  *   // bundleInFreeDebug: true,
>  *   // bundleInPaidRelease: true,
>  *   // bundleInBeta: true,
>  *
>  *   // whether to disable dev mode in custom build variants (by default only disabled in release)
>  *   // for example: to disable dev mode in the staging build type (if configured)
>  *   devDisabledInStaging: true,
>  *   // The configuration property can be in the following formats
>  *   //         'devDisabledIn${productFlavor}${buildType}'
>  *   //         'devDisabledIn${buildType}'
>  *
>  *   // the root of your project, i.e. where "package.json" lives
>  *   root: "../../",
>  *
>  *   // where to put the JS bundle asset in debug mode
>  *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
>  *
>  *   // where to put the JS bundle asset in release mode
>  *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
>  *
>  *   // where to put drawable resources / React Native assets, e.g. the ones you use via
>  *   // require('./image.png')), in debug mode
>  *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
>  *
>  *   // where to put drawable resources / React Native assets, e.g. the ones you use via
>  *   // require('./image.png')), in release mode
>  *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
>  *
>  *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
>  *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
>  *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
>  *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
>  *   // for example, you might want to remove it from here.
>  *   inputExcludes: ["android/**", "ios/**"],
>  *
>  *   // override which node gets called and with what additional arguments
>  *   nodeExecutableAndArgs: ["node"],
>  *
>  *   // supply additional arguments to the packager
>  *   extraPackagerArgs: []
>  * ]
>  */
> 
> project.ext.react = [
>     entryFile: "index.js"
> ]
> 
> apply from: "../../node_modules/react-native/react.gradle"
> apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
> project.ext.vectoricons = [
>     iconFontNames: [ 'MaterialIcons.ttf', 'MaterialCommunityIcons.ttf' ] // Name of the font files you want to copy
> ]
> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
> 
> /**
>  * Set this to true to create two separate APKs instead of one:
>  *   - An APK that only works on ARM devices
>  *   - An APK that only works on x86 devices
>  * The advantage is the size of the APK is reduced by about 4MB.
>  * Upload all the APKs to the Play Store and people will download
>  * the correct one based on the CPU architecture of their device.
>  */
> def enableSeparateBuildPerCPUArchitecture = false
> 
> /**
>  * Run Proguard to shrink the Java bytecode in release builds.
>  */
> def enableProguardInReleaseBuilds = false
> 
> android {
>     configurations.all {
>         resolutionStrategy {
>             failOnVersionConflict()
>             force 'com.android.support:appcompat-v7:27.1.1', 'com.android.support:support-annotations:27.1.1', 'com.android.support:support-v4:27.1.1','com.squareup.okhttp3:okhttp:3.6.0', 'com.squareup.okio:okio:1.9.0', 'com.android.support:recyclerview-v7:27.1.1', 'com.google.code.findbugs:jsr305:3.0.0', 'com.squareup.okhttp:okhttp:2.5.0', 'com.fasterxml.jackson.core:jackson-core:2.8.7'
>         }
>     }
>     compileSdkVersion 26
>     buildToolsVersion "26.0.3"
> 
>     defaultConfig {
>         applicationId "com.truckepal"
>         minSdkVersion 16
>         targetSdkVersion 25
>         versionCode 16
>         versionName "1.1"
>         ndk {
>             abiFilters "armeabi-v7a", "x86"
>         }
>         multiDexEnabled true
>         // Detox
>         // testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
>     signingConfigs {
>         release {
>             if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
>                 storeFile file(MYAPP_RELEASE_STORE_FILE)
>                 storePassword MYAPP_RELEASE_STORE_PASSWORD
>                 keyAlias MYAPP_RELEASE_KEY_ALIAS
>                 keyPassword MYAPP_RELEASE_KEY_PASSWORD
>             }
>         }
>     }
>     splits {
>         abi {
>             reset()
>             enable enableSeparateBuildPerCPUArchitecture
>             universalApk false  // If true, also generate a universal APK
>             include "armeabi-v7a", "x86"
>         }
>     }
>     buildTypes {
>         debug {
>             buildConfigField "String", "CODEPUSH_KEY", '""'
>         }
>         releaseStaging {
>             buildConfigField "String", "CODEPUSH_KEY", '"d0ztU8ffvT04NUUEOu5nUk-H5yYtd893ee1a-fd0d-48e9-bbfa-b15dccdcf752"'
>         }
>         release {
>             minifyEnabled enableProguardInReleaseBuilds
>             proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
>             signingConfig signingConfigs.release
>             buildConfigField "String", "CODEPUSH_KEY", '"8k_tWB0DXsuzZCvUq8KrbfeYL2iMd893ee1a-fd0d-48e9-bbfa-b15dccdcf752"'
>         }
>     }
>     // applicationVariants are e.g. debug, release
>     applicationVariants.all { variant ->
>         variant.outputs.each { output ->
>             // For each separate APK per architecture, set a unique version code as described here:
>             // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
>             def versionCodes = ["armeabi-v7a":1, "x86":2]
>             def abi = output.getFilter(OutputFile.ABI)
>             if (abi != null) {  // null for the universal-debug, universal-release variants
>                 output.versionCodeOverride =
>                         versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
>             }
>         }
>     }
>     dexOptions {
>         jumboMode true
>     }
> }
> 
> dependencies {
>     compile project(':react-native-vector-icons')
>     compile(project(':react-native-firebase')) {
>         transitive = false
>     }
>     compile project(':react-native-code-push')
>     compile (project(':react-native-firebase')) {
>         transitive = false
>         exclude group: "com.google.android.gms" 
>     }
>     compile project(':react-native-image-picker')    
>     compile project(':react-native-hypertrack')
>     compile fileTree(dir: "libs", include: ["*.jar"])
>     compile "com.android.support:appcompat-v7:26.1.0"
>     compile "com.facebook.react:react-native:+"  // From node_modules
>     // androidTestCompile(project(path: ":detox", configuration: "oldOkhttpDebug"), {
>     //     exclude group: 'com.android.support', module: 'support-annotations'
>     //     exclude group: 'com.squareup.okhttp3', module: 'okhttp'
>     //     exclude group: 'com.squareup.okio', module: 'okio'
>     // })
>     // androidTestCompile 'com.squareup.okhttp3:okhttp:3.6.0'
>     // androidTestCompile 'com.squareup.okio:okio:1.9.0'
>     // react-native-firebase
>     compile ("com.google.android.gms:play-services-base:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.android.gms:play-services-gcm:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.android.gms:play-services-location:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.android.gms:play-services-maps:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.android.gms:play-services-places:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.firebase:firebase-core:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.firebase:firebase-messaging:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.firebase:firebase-crash:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.firebase:firebase-database:11.4.2") {
>         force = true;
>     }
>     compile ("com.google.firebase:firebase-auth:11.4.2") {
>         force = true;
>     }
> }
> 
> // react-native-firebase
> apply plugin: 'com.google.gms.google-services'
> 
> // Run this once to be able to run the application with BUCK
> // puts all compile dependencies into folder libs for BUCK to use
> task copyDownloadableDepsToLibs(type: Copy) {
>     from configurations.compile
>     into 'libs'
> }
>

**Comment by amanjain08** [comment]
The error shows up because of RN breaking change

Try to remove **Override** annotation inside the 
**/node_modules/react-native-hypertrack/android/src/main/java/io/hypertrack/RNHyperTrackPackage.java**

**Before**
 
    public class RNHyperTrackPackage implements ReactPackage {
    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
      return Arrays.<NativeModule>asList(new RNHyperTrackModule(reactContext));
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
      return Collections.emptyList();
    }
    }

**After**

public class RNHyperTrackPackage implements ReactPackage {

    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
      return Arrays.<NativeModule>asList(new RNHyperTrackModule(reactContext));
    }


    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }


    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
      return Collections.emptyList();
    }
    }
